Streamline gerrit/jenkins tooling

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -315,6 +315,28 @@ do
 done
 }
 
+# Get current change ids
+gerrit_current_change_ids() {
+    git_dir="$(git rev-parse --show-toplevel)"
+    # remote branch
+    gerrit_branch="$(grep "^defaultbranch=" "${git_dir}/.gitreview" | cut -d = -f 2)"
+    gerrit_remote="$(grep "^defaultremote=" "${git_dir}/.gitreview" | cut -d = -f 2)"
+
+    gerrit_remote_raw=$(git config --local remote.${gerrit_remote}.url)
+    elements=("${(@s:/:)gerrit_remote_raw}")
+    gerrit_project=${elements[-1]}
+    elements[-1]=()
+    gerrit_url=${(j./.)elements}
+
+    elements=("${(@s.:.)gerrit_url}")
+    gerrit_port=${elements[-1]}
+    gerrit_url=${${elements[-2]}:gs./.}
+    change_ids=( "${(@f)$(git log ${gerrit_remote}/${gerrit_branch}..HEAD \
+        | awk '$1 ~ /^Change-Id:/ { print $2 }')}" )
+
+    printf "%s\n" "${change_ids[@]}"
+}
+
 # Check if the last patch level of any open changeset was last uploaded by someone else.
 #
 # This should make it harder to accidentally overwrite other peoples edits.
@@ -333,8 +355,7 @@ gerrit_check_pre_review() {
     elements=("${(@s.:.)gerrit_url}")
     gerrit_port=${elements[-1]}
     gerrit_url=${${elements[-2]}:gs./.}
-    change_ids=( "${(@f)$(git log ${gerrit_remote}/${gerrit_branch}..HEAD \
-        | awk '$1 ~ /^Change-Id:/ { print $2 }')}" )
+    change_ids=( "${(@f)$(gerrit_current_change_ids)}" )
     committers=( "${(@f)$(git log --format="%cn <%ce>" "${gerrit_remote}/${gerrit_branch}..HEAD")}" )
 
     if (( ${#change_ids} != ${#committers} )); then
@@ -359,7 +380,7 @@ gerrit_check_pre_review() {
         uploader="${uploader_name} <${uploader_mail}>"
 
         if [[ "${uploader}" == "null <null>" ]]; then
-            echo "WARNING: Info on changeset ${change_id} not current anymore!" >&2
+            echo "WARNING: Info on changeset ${change_id} not current anymore! Fetch from review!" >&2
         fi
 
         if [[ "${committer}" != "${uploader}" ]]; then
@@ -512,7 +533,7 @@ jrest() {
 #   <build number>  Log from which build to get [default: latest]. Can be set
 #                   to -n to get the n-th latest build log.
 #
-get_jenkins_log() {
+jenkins_get_log() {
     local project
     local build_num
     local logname
@@ -579,7 +600,7 @@ get_jenkins_log() {
     echo "${logname}"
 }
 
-get_changes() {
+gerrit_get_changes() {
     grest "/a/changes/?q=$*"  | tail -n +2 | jq -r "map(.id) | .[]"
 }
 
@@ -593,8 +614,51 @@ clang_format_head() {
     git status
 }
 
-build_this() {
-    grest POST /a/changes/$(change_id)/revisions/current/review message=BUILD_THIS
+gerrit_change_id_head()
+{
+    git log -n 1 | awk '\$1 ~ /Change-Id:/ { print \$2 }' | tr -d '\n'
+}
+
+# Post a message (-m) to the given change_id (-c)
+#
+# If change id is not specified, take the current head.
+#
+# Args:
+#   -c change_id
+#   -l labels
+#   -m message
+gerrit_post_message() {
+    local change_id
+    local message
+    local labels
+    change_id="head"
+    message=""
+    while getopts ":c:l:m:" opts; do
+        case "${opts}" in
+            c)
+                change_id="${OPTARG}"
+                ;;
+            m)  message="${OPTARG}"
+                ;;
+            l)  labels="${OPTARG}"
+                ;;
+            *)
+                echo "Invalid argument: ${opts}" >&2
+                return 1
+                ;;
+        esac
+    done
+    shift $(( OPTIND - 1 ))
+
+    if [ "${change_id}" = "head" ]; then
+        change_id="$(change_id_head)"
+    fi
+
+    grest POST /a/changes/${change_id}/revisions/current/review "message=${message}" "labels:='${labels}'"
+}
+
+gerrit_build_this() {
+    gerrit_post_message -m "BUILD_THIS"
 }
 
 get_bpm() {
