get_jenkins_log: Add capability for artifcats

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -417,12 +417,15 @@ jrest() {
 }
 
 # Usage:
-#   get_jenkins_log <project> [<build number>]
+#   get_jenkins_log [-a <artifact] <project> [<build number>]
 #
 #   Fetches and echoes the name of the file in which the log is present. Log
 #   will only be fetched if logfile does not exist.
 #
 # Args:
+#   -a <artifact>   Get specific aritifact
+#                   (example: errors_concretization.log).
+#
 #   <project>       Project to fetch
 #
 #   <build number>  Log from which build to get [default: latest].
@@ -431,11 +434,27 @@ get_jenkins_log() {
     local project
     local build_num
     local logname
+    local artifact
+    artifact=""
+
+    while getopts ":a:" opts; do
+        case "${opts}" in
+            a)
+                artifact="${OPTARG}"
+                ;;
+            *)
+                echo "Invalid argument: ${OPTARG}" >&2
+                return 1
+                ;;
+        esac
+    done
+    shift $(( OPTIND - 1 ))
+
     if (( $# > 0 )); then
         project="$1"
     else
         echo "Need to specify project!" &>2
-        return -1
+        return 1
     fi
     shift
 
@@ -444,10 +463,18 @@ get_jenkins_log() {
     else
         build_num=$(jrest GET /job/${project}/api/json | jq ".builds | .[1] | .number")
     fi
-    logname="${TMPDIR:-/tmp}/${project}_${build_num}.log"
+    if (( ${#artifact} > 0 )); then
+        logname="${TMPDIR:-/tmp}/${project}_${build_num}_${artifact}"
+    else
+        logname="${TMPDIR:-/tmp}/${project}_${build_num}.log"
+    fi
 
     if [ ! -f "${logname}" ]; then
-        jrest GET "/job/${project}/${build_num}/consoleText" > "${logname}"
+        if (( ${#artifact} > 0 )); then
+            jrest GET "/job/${project}/${build_num}/artifact/${artifact}" > "${logname}" || rm ${logname}
+        else
+            jrest GET "/job/${project}/${build_num}/consoleText" > "${logname}"
+        fi
     fi
     echo "${logname}"
 }
